{
    "size":0,
    "query":{
       "bool":{
          "must":[
             {
                "terms":{
                   "pfno":[
                      "12845",
                      "23884"
                   ],
                   "boost":1.0
                }
             }
          ],
          "filter":[
             {
                "range":{
                   "vt":{
                      "from":"2020-03-01T00:00:00+0900",
                      "to":"2020-05-05T23:59:59+0900",
                      "include_lower":true,
                      "include_upper":true,
                      "boost":1.0
                   }
                }
             }
          ],
          "must_not":[
             {
                "term":{
                   "items.pnc":{
                      "value":"",
                      "boost":1.0
                   }
                }
             },
             {
                "term":{
                   "campaigns.cc":{
                      "value":"",
                      "boost":1.0
                   }
                }
             }
          ],
          "adjust_pure_negative":true,
          "boost":1.0
       }
    },
    "aggregations":{
       "by_campaign":{
          "terms":{
             "field":"campaigns.cc",
             "size":10,
             "min_doc_count":1,
             "shard_min_doc_count":0,
             "show_term_doc_count_error":false,
             "order":[
                {
                   "_count":"desc"
                },
                {
                   "_key":"asc"
                }
             ]
          },
          "aggregations":{
             "pageviews":{
                "value_count":{
                   "field":"_id"
                }
             },
             "visits":{
                "cardinality":{
                   "field":"sid"
                }
             },
             "visitors":{
                "cardinality":{
                   "field":"uid"
                }
             },
             "duration":{
                "sum":{
                   "field":"duration",
                   "missing":0
                }
             },
             "cartin":{
                "sum":{
                   "script":{
                      "source":"doc['pi'].size() != 0 && doc['pi'].value == 'OCI' ? 1 : 0",
                      "lang":"painless"
                   },
                   "missing":0
                }
             },
             "buy":{
                "sum":{
                   "script":{
                      "source":"doc['pi'].size() != 0 && doc['pi'].value == 'ODR' ? 1 : 0",
                      "lang":"painless"
                   },
                   "missing":0
                }
             },
             "revenue":{
                "sum":{
                   "field":"rvn.oa"
                }
             },
             "register":{
                "sum":{
                   "script":{
                      "source":"doc['pi'].size() != 0 && doc['pi'].value == 'RGR' ? 1 : 0",
                      "lang":"painless"
                   },
                   "missing":0
                }
             },
             "solditem":{
                "cardinality":{
                   "field":"rvn.op"
                }
             }
          }
       }
    }
 }