{
    "took":7,
    "timed_out":false,
    "_shards":{
       "total":45,
       "successful":45,
       "skipped":0,
       "failed":0
    },
    "hits":{
       "total":0,
       "max_score":null,
       "hits":[
 
       ]
    },
    "aggregations":{
       "sterms#by_campaign":{
          "doc_count_error_upper_bound":0,
          "sum_other_doc_count":0,
          "buckets":[
             {
                "key":"4444",
                "doc_count":44,
                "sum#duration":{
                   "value":1975.0
                },
                "cardinality#visitors":{
                   "value":1
                },
                "cardinality#visits":{
                   "value":4
                },
                "sum#revenue":{
                   "value":7600.0
                },
                "value_count#pageviews":{
                   "value":44
                },
                "sum#buy":{
                   "value":3.0
                },
                "sum#cartin":{
                   "value":0.0
                },
                "cardinality#solditem":{
                   "value":6
                },
                "sum#register":{
                   "value":1.0
                }
             },
             {
                "key":"8888",
                "doc_count":20,
                "sum#duration":{
                   "value":901.0
                },
                "cardinality#visitors":{
                   "value":2
                },
                "cardinality#visits":{
                   "value":2
                },
                "sum#revenue":{
                   "value":3300.0
                },
                "value_count#pageviews":{
                   "value":20
                },
                "sum#buy":{
                   "value":2.0
                },
                "sum#cartin":{
                   "value":0.0
                },
                "cardinality#solditem":{
                   "value":3
                },
                "sum#register":{
                   "value":1.0
                }
             },
             {
                "key":"9999",
                "doc_count":16,
                "sum#duration":{
                   "value":195.0
                },
                "cardinality#visitors":{
                   "value":2
                },
                "cardinality#visits":{
                   "value":3
                },
                "sum#revenue":{
                   "value":3300.0
                },
                "value_count#pageviews":{
                   "value":16
                },
                "sum#buy":{
                   "value":1.0
                },
                "sum#cartin":{
                   "value":0.0
                },
                "cardinality#solditem":{
                   "value":3
                },
                "sum#register":{
                   "value":0.0
                }
             },
             {
                "key":"7777",
                "doc_count":12,
                "sum#duration":{
                   "value":17.0
                },
                "cardinality#visitors":{
                   "value":1
                },
                "cardinality#visits":{
                   "value":1
                },
                "sum#revenue":{
                   "value":3100.0
                },
                "value_count#pageviews":{
                   "value":12
                },
                "sum#buy":{
                   "value":1.0
                },
                "sum#cartin":{
                   "value":0.0
                },
                "cardinality#solditem":{
                   "value":3
                },
                "sum#register":{
                   "value":0.0
                }
             }
          ]
       }
    }
 }