{
    "data":[
       {
          "campaign":"4444",
          "pageviews":44,
          "visits":4,
          "visitors":1,
          "duration":1975,
          "register":1,
          "revenue":7600,
          "buy":3,
          "solditem":6,
          "cartin":0
       },
       {
          "campaign":"8888",
          "pageviews":20,
          "visits":2,
          "visitors":2,
          "duration":901,
          "register":1,
          "revenue":3300,
          "buy":2,
          "solditem":3,
          "cartin":0
       },
       {
          "campaign":"9999",
          "pageviews":16,
          "visits":3,
          "visitors":2,
          "duration":195,
          "register":0,
          "revenue":3300,
          "buy":1,
          "solditem":3,
          "cartin":0
       },
       {
          "campaign":"7777",
          "pageviews":12,
          "visits":1,
          "visitors":1,
          "duration":17,
          "register":0,
          "revenue":3100,
          "buy":1,
          "solditem":3,
          "cartin":0
       }
    ]
 }