{
    "index":"pageview-*",
    "body":{
       "query":{
          "bool":{
             "must":{
                "terms":{
                   "pfno":[
                      "12845",
                      "23884"
                   ]
                }
             },
             "must_not":[
                {
                   "term":{
                      "items.pnc":""
                   }
                },
                {
                   "term":{
                      "campaigns.cc":""
                   }
                }
             ],
             "filter":{
                "range":{
                   "vt":{
                      "gte":"2020-03-01T00:00:00+0900",
                      "lte":"2020-05-05T23:59:59+0900"
                   }
                }
             }
          }
       },
       "aggs":{
          "by_campaign":{
             "terms":{
                "field":"campaigns.cc"
             },
             "aggs":{
                "pageviews":{
                   "value_count":{
                      "field":"_id"
                   }
                },
                "visits":{
                   "cardinality":{
                      "field":"sid"
                   }
                },
                "visitors":{
                   "cardinality":{
                      "field":"uid"
                   }
                },
                "duration":{
                   "sum":{
                      "field":"duration",
                      "missing":0
                   }
                },
                "cartin":{
                   "sum":{
                      "script":{
                         "source":"doc['pi'].size() != 0 && doc['pi'].value == 'OCI' ? 1 : 0"
                      }
                   }
                },
                "buy":{
                   "sum":{
                      "script":{
                         "source":"doc['pi'].size() != 0 && doc['pi'].value == 'ODR' ? 1 : 0"
                      }
                   }
                },
                "revenue":{
                   "sum":{
                      "field":"rvn.oa"
                   }
                },
                "register":{
                   "sum":{
                      "script":{
                         "source":"doc['pi'].size() != 0 && doc['pi'].value == 'RGR' ? 1 : 0"
                      }
                   }
                },
                "solditem":{
                   "cardinality":{
                      "field":"rvn.op"
                   }
                }
             }
          }
       }
    }
 }