{
   "took":12,
   "timed_out":false,
   "_shards":{
      "total":45,
      "successful":45,
      "skipped":0,
      "failed":0
   },
   "hits":{
      "total":0,
      "max_score":null,
      "hits":[

      ]
   },
   "aggregations":{
      "sterms#by_dimension":{
         "doc_count_error_upper_bound":0,
         "sum_other_doc_count":0,
         "buckets":[
            {
               "key":"PLV",
               "doc_count":132,
               "sum#duration":{
                  "value":2294.0
               },
               "cardinality#visitors":{
                  "value":14
               },
               "cardinality#visits":{
                  "value":27
               },
               "value_count#pageviews":{
                  "value":132
               }
            },
            {
               "key":"PDV",
               "doc_count":120,
               "sum#duration":{
                  "value":3496.0
               },
               "cardinality#visitors":{
                  "value":14
               },
               "cardinality#visits":{
                  "value":26
               },
               "value_count#pageviews":{
                  "value":120
               }
            },
            {
               "key":"OCV",
               "doc_count":35,
               "sum#duration":{
                  "value":96.0
               },
               "cardinality#visitors":{
                  "value":9
               },
               "cardinality#visits":{
                  "value":15
               },
               "value_count#pageviews":{
                  "value":35
               }
            },
            {
               "key":"ODF",
               "doc_count":15,
               "sum#duration":{
                  "value":59.0
               },
               "cardinality#visitors":{
                  "value":7
               },
               "cardinality#visits":{
                  "value":13
               },
               "value_count#pageviews":{
                  "value":15
               }
            },
            {
               "key":"ODR",
               "doc_count":14,
               "sum#duration":{
                  "value":1238.0
               },
               "cardinality#visitors":{
                  "value":7
               },
               "cardinality#visits":{
                  "value":13
               },
               "value_count#pageviews":{
                  "value":14
               }
            },
            {
               "key":"LIF",
               "doc_count":7,
               "sum#duration":{
                  "value":23.0
               },
               "cardinality#visitors":{
                  "value":5
               },
               "cardinality#visits":{
                  "value":5
               },
               "value_count#pageviews":{
                  "value":7
               }
            },
            {
               "key":"RGI",
               "doc_count":7,
               "sum#duration":{
                  "value":16.0
               },
               "cardinality#visitors":{
                  "value":5
               },
               "cardinality#visits":{
                  "value":6
               },
               "value_count#pageviews":{
                  "value":7
               }
            },
            {
               "key":"RGF",
               "doc_count":6,
               "sum#duration":{
                  "value":14.0
               },
               "cardinality#visitors":{
                  "value":5
               },
               "cardinality#visits":{
                  "value":6
               },
               "value_count#pageviews":{
                  "value":6
               }
            },
            {
               "key":"RGR",
               "doc_count":6,
               "sum#duration":{
                  "value":9.0
               },
               "cardinality#visitors":{
                  "value":5
               },
               "cardinality#visits":{
                  "value":6
               },
               "value_count#pageviews":{
                  "value":6
               }
            },
            {
               "key":"LIR",
               "doc_count":4,
               "sum#duration":{
                  "value":4.0
               },
               "cardinality#visitors":{
                  "value":4
               },
               "cardinality#visits":{
                  "value":4
               },
               "value_count#pageviews":{
                  "value":4
               }
            },
            {
               "key":"2E1",
               "doc_count":1,
               "sum#duration":{
                  "value":4.0
               },
               "cardinality#visitors":{
                  "value":1
               },
               "cardinality#visits":{
                  "value":1
               },
               "value_count#pageviews":{
                  "value":1
               }
            }
         ]
      }
   }
}