{
   "data":[
      {
         "dimension":"PLV",
         "pageviews":132,
         "visits":27,
         "visitors":14,
         "duration":2294
      },
      {
         "dimension":"PDV",
         "pageviews":120,
         "visits":26,
         "visitors":14,
         "duration":3496
      },
      {
         "dimension":"OCV",
         "pageviews":35,
         "visits":15,
         "visitors":9,
         "duration":96
      },
      {
         "dimension":"ODF",
         "pageviews":15,
         "visits":13,
         "visitors":7,
         "duration":59
      },
      {
         "dimension":"ODR",
         "pageviews":14,
         "visits":13,
         "visitors":7,
         "duration":1238
      },
      {
         "dimension":"LIF",
         "pageviews":7,
         "visits":5,
         "visitors":5,
         "duration":23
      },
      {
         "dimension":"RGI",
         "pageviews":7,
         "visits":6,
         "visitors":5,
         "duration":16
      },
      {
         "dimension":"RGF",
         "pageviews":6,
         "visits":6,
         "visitors":5,
         "duration":14
      },
      {
         "dimension":"RGR",
         "pageviews":6,
         "visits":6,
         "visitors":5,
         "duration":9
      },
      {
         "dimension":"LIR",
         "pageviews":4,
         "visits":4,
         "visitors":4,
         "duration":4
      },
      {
         "dimension":"2E1",
         "pageviews":1,
         "visits":1,
         "visitors":1,
         "duration":4
      }
   ]
}