searchResponse: 




{
    "took":16,
    "timed_out":false,
    "_shards":{
       "total":45,
       "successful":45,
       "skipped":0,
       "failed":0
    },
    "hits":{
       "total":0,
       "max_score":null,
       "hits":[
 
       ]
    },
    "aggregations":{
       "sterms#by_dimension":{
          "doc_count_error_upper_bound":0,
          "sum_other_doc_count":0,
          "buckets":[
             {
                "key":"AFK000",
                "doc_count":21,
                "sum#duration":{
                   "value":83.0
                },
                "cardinality#visitors":{
                   "value":7
                },
                "cardinality#visits":{
                   "value":10
                },
                "value_count#pageviews":{
                   "value":21
                }
             },
             {
                "key":"CFK000",
                "doc_count":19,
                "sum#duration":{
                   "value":1473.0
                },
                "cardinality#visitors":{
                   "value":3
                },
                "cardinality#visits":{
                   "value":3
                },
                "value_count#pageviews":{
                   "value":19
                }
             },
             {
                "key":"BFK000",
                "doc_count":7,
                "sum#duration":{
                   "value":1045.0
                },
                "cardinality#visitors":{
                   "value":4
                },
                "cardinality#visits":{
                   "value":5
                },
                "value_count#pageviews":{
                   "value":7
                }
             },
             {
                "key":"AGK000",
                "doc_count":6,
                "sum#duration":{
                   "value":177.0
                },
                "cardinality#visitors":{
                   "value":5
                },
                "cardinality#visits":{
                   "value":6
                },
                "value_count#pageviews":{
                   "value":6
                }
             },
             {
                "key":"AHL000",
                "doc_count":6,
                "sum#duration":{
                   "value":437.0
                },
                "cardinality#visitors":{
                   "value":4
                },
                "cardinality#visits":{
                   "value":4
                },
                "value_count#pageviews":{
                   "value":6
                }
             },
             {
                "key":"AFK001",
                "doc_count":5,
                "sum#duration":{
                   "value":7.0
                },
                "cardinality#visitors":{
                   "value":3
                },
                "cardinality#visits":{
                   "value":4
                },
                "value_count#pageviews":{
                   "value":5
                }
             },
             {
                "key":"AHK000",
                "doc_count":4,
                "sum#duration":{
                   "value":4.0
                },
                "cardinality#visitors":{
                   "value":3
                },
                "cardinality#visits":{
                   "value":4
                },
                "value_count#pageviews":{
                   "value":4
                }
             },
             {
                "key":"AHM000",
                "doc_count":4,
                "sum#duration":{
                   "value":5.0
                },
                "cardinality#visitors":{
                   "value":3
                },
                "cardinality#visits":{
                   "value":3
                },
                "value_count#pageviews":{
                   "value":4
                }
             },
             {
                "key":"BFK001",
                "doc_count":4,
                "sum#duration":{
                   "value":8.0
                },
                "cardinality#visitors":{
                   "value":3
                },
                "cardinality#visits":{
                   "value":4
                },
                "value_count#pageviews":{
                   "value":4
                }
             },
             {
                "key":"AFK002",
                "doc_count":3,
                "sum#duration":{
                   "value":4.0
                },
                "cardinality#visitors":{
                   "value":3
                },
                "cardinality#visits":{
                   "value":3
                },
                "value_count#pageviews":{
                   "value":3
                }
             },
             {
                "key":"AFL000",
                "doc_count":3,
                "sum#duration":{
                   "value":49.0
                },
                "cardinality#visitors":{
                   "value":3
                },
                "cardinality#visits":{
                   "value":3
                },
                "value_count#pageviews":{
                   "value":3
                }
             },
             {
                "key":"AFL002",
                "doc_count":3,
                "sum#duration":{
                   "value":4.0
                },
                "cardinality#visitors":{
                   "value":2
                },
                "cardinality#visits":{
                   "value":3
                },
                "value_count#pageviews":{
                   "value":3
                }
             },
             {
                "key":"AFM001",
                "doc_count":3,
                "sum#duration":{
                   "value":2.0
                },
                "cardinality#visitors":{
                   "value":3
                },
                "cardinality#visits":{
                   "value":3
                },
                "value_count#pageviews":{
                   "value":3
                }
             },
             {
                "key":"AGM000",
                "doc_count":3,
                "sum#duration":{
                   "value":15.0
                },
                "cardinality#visitors":{
                   "value":2
                },
                "cardinality#visits":{
                   "value":2
                },
                "value_count#pageviews":{
                   "value":3
                }
             },
             {
                "key":"AGL003",
                "doc_count":2,
                "sum#duration":{
                   "value":0.0
                },
                "cardinality#visitors":{
                   "value":1
                },
                "cardinality#visits":{
                   "value":1
                },
                "value_count#pageviews":{
                   "value":2
                }
             },
             {
                "key":"AHK003",
                "doc_count":2,
                "sum#duration":{
                   "value":2.0
                },
                "cardinality#visitors":{
                   "value":1
                },
                "cardinality#visits":{
                   "value":1
                },
                "value_count#pageviews":{
                   "value":2
                }
             },
             {
                "key":"BFK003",
                "doc_count":2,
                "sum#duration":{
                   "value":4.0
                },
                "cardinality#visitors":{
                   "value":1
                },
                "cardinality#visits":{
                   "value":2
                },
                "value_count#pageviews":{
                   "value":2
                }
             },
             {
                "key":"BFL003",
                "doc_count":2,
                "sum#duration":{
                   "value":1.0
                },
                "cardinality#visitors":{
                   "value":2
                },
                "cardinality#visits":{
                   "value":2
                },
                "value_count#pageviews":{
                   "value":2
                }
             },
             {
                "key":"BHM000",
                "doc_count":2,
                "sum#duration":{
                   "value":2.0
                },
                "cardinality#visitors":{
                   "value":2
                },
                "cardinality#visits":{
                   "value":2
                },
                "value_count#pageviews":{
                   "value":2
                }
             },
             {
                "key":"CFK001",
                "doc_count":2,
                "sum#duration":{
                   "value":3.0
                },
                "cardinality#visitors":{
                   "value":2
                },
                "cardinality#visits":{
                   "value":2
                },
                "value_count#pageviews":{
                   "value":2
                }
             },
             {
                "key":"AFK003",
                "doc_count":1,
                "sum#duration":{
                   "value":3.0
                },
                "cardinality#visitors":{
                   "value":1
                },
                "cardinality#visits":{
                   "value":1
                },
                "value_count#pageviews":{
                   "value":1
                }
             },
             {
                "key":"AFL001",
                "doc_count":1,
                "sum#duration":{
                   "value":2.0
                },
                "cardinality#visitors":{
                   "value":1
                },
                "cardinality#visits":{
                   "value":1
                },
                "value_count#pageviews":{
                   "value":1
                }
             },
             {
                "key":"AFL003",
                "doc_count":1,
                "sum#duration":{
                   "value":0.0
                },
                "cardinality#visitors":{
                   "value":1
                },
                "cardinality#visits":{
                   "value":1
                },
                "value_count#pageviews":{
                   "value":1
                }
             },
             {
                "key":"AGK001",
                "doc_count":1,
                "sum#duration":{
                   "value":1.0
                },
                "cardinality#visitors":{
                   "value":1
                },
                "cardinality#visits":{
                   "value":1
                },
                "value_count#pageviews":{
                   "value":1
                }
             },
             {
                "key":"AGL000",
                "doc_count":1,
                "sum#duration":{
                   "value":0.0
                },
                "cardinality#visitors":{
                   "value":1
                },
                "cardinality#visits":{
                   "value":1
                },
                "value_count#pageviews":{
                   "value":1
                }
             },
             {
                "key":"AGL001",
                "doc_count":1,
                "sum#duration":{
                   "value":3.0
                },
                "cardinality#visitors":{
                   "value":1
                },
                "cardinality#visits":{
                   "value":1
                },
                "value_count#pageviews":{
                   "value":1
                }
             },
             {
                "key":"AGM002",
                "doc_count":1,
                "sum#duration":{
                   "value":0.0
                },
                "cardinality#visitors":{
                   "value":1
                },
                "cardinality#visits":{
                   "value":1
                },
                "value_count#pageviews":{
                   "value":1
                }
             },
             {
                "key":"AGM004",
                "doc_count":1,
                "sum#duration":{
                   "value":0.0
                },
                "cardinality#visitors":{
                   "value":1
                },
                "cardinality#visits":{
                   "value":1
                },
                "value_count#pageviews":{
                   "value":1
                }
             },
             {
                "key":"AHL003",
                "doc_count":1,
                "sum#duration":{
                   "value":2.0
                },
                "cardinality#visitors":{
                   "value":1
                },
                "cardinality#visits":{
                   "value":1
                },
                "value_count#pageviews":{
                   "value":1
                }
             },
             {
                "key":"AHM002",
                "doc_count":1,
                "sum#duration":{
                   "value":2.0
                },
                "cardinality#visitors":{
                   "value":1
                },
                "cardinality#visits":{
                   "value":1
                },
                "value_count#pageviews":{
                   "value":1
                }
             },
             {
                "key":"BFM002",
                "doc_count":1,
                "sum#duration":{
                   "value":144.0
                },
                "cardinality#visitors":{
                   "value":1
                },
                "cardinality#visits":{
                   "value":1
                },
                "value_count#pageviews":{
                   "value":1
                }
             },
             {
                "key":"BFM003",
                "doc_count":1,
                "sum#duration":{
                   "value":2.0
                },
                "cardinality#visitors":{
                   "value":1
                },
                "cardinality#visits":{
                   "value":1
                },
                "value_count#pageviews":{
                   "value":1
                }
             },
             {
                "key":"BGK004",
                "doc_count":1,
                "sum#duration":{
                   "value":3.0
                },
                "cardinality#visitors":{
                   "value":1
                },
                "cardinality#visits":{
                   "value":1
                },
                "value_count#pageviews":{
                   "value":1
                }
             },
             {
                "key":"CFL003",
                "doc_count":1,
                "sum#duration":{
                   "value":3.0
                },
                "cardinality#visitors":{
                   "value":1
                },
                "cardinality#visits":{
                   "value":1
                },
                "value_count#pageviews":{
                   "value":1
                }
             },
             {
                "key":"CGL000",
                "doc_count":1,
                "sum#duration":{
                   "value":0.0
                },
                "cardinality#visitors":{
                   "value":1
                },
                "cardinality#visits":{
                   "value":1
                },
                "value_count#pageviews":{
                   "value":1
                }
             },
             {
                "key":"CHK000",
                "doc_count":1,
                "sum#duration":{
                   "value":3.0
                },
                "cardinality#visitors":{
                   "value":1
                },
                "cardinality#visits":{
                   "value":1
                },
                "value_count#pageviews":{
                   "value":1
                }
             },
             {
                "key":"CHM000",
                "doc_count":1,
                "sum#duration":{
                   "value":3.0
                },
                "cardinality#visitors":{
                   "value":1
                },
                "cardinality#visits":{
                   "value":1
                },
                "value_count#pageviews":{
                   "value":1
                }
             }
          ]
       }
    }
 }