{
    "index":"pageview-*",
    "body":{
       "query":{
          "bool":{
             "must":{
                "terms":{
                   "pfno":[
                      "12845",
                      "23884"
                   ]
                }
             },
             "filter":{
                "range":{
                   "vt":{
                      "gte":"2020-03-01T00:00:00+0900",
                      "lte":"2020-04-30T23:59:59+0900"
                   }
                }
             }
          }
       },
       "aggs":{
          "by_date":{
             "date_histogram":{
                "field":"vt",
                "fixed_interval":"1d",
                "format":"yyyy-MM-dd",
                "time_zone":"Asia\/Seoul",
                "min_doc_count":0
             },
             "aggs":{
                "pageviews":{
                   "value_count":{
                      "field":"_id"
                   }
                },
                "visits":{
                   "cardinality":{
                      "field":"sid"
                   }
                },
                "visitors":{
                   "cardinality":{
                      "field":"uid"
                   }
                },
                "ips":{
                   "cardinality":{
                      "field":"locations.ip"
                   }
                }
             }
          }
       }
    }
 }