{
    "took":11,
    "timed_out":false,
    "_shards":{
       "total":45,
       "successful":45,
       "skipped":0,
       "failed":0
    },
    "hits":{
       "total":0,
       "max_score":null,
       "hits":[
 
       ]
    },
    "aggregations":{
       "date_histogram#by_date":{
          "buckets":[
             {
                "key_as_string":"2020-03-19",
                "key":1584543600000,
                "doc_count":12,
                "cardinality#visitors":{
                   "value":1
                },
                "cardinality#visits":{
                   "value":1
                },
                "value_count#pageviews":{
                   "value":12
                },
                "cardinality#ips":{
                   "value":1
                }
             },
             {
                "key_as_string":"2020-03-20",
                "key":1584630000000,
                "doc_count":0,
                "cardinality#visitors":{
                   "value":0
                },
                "cardinality#visits":{
                   "value":0
                },
                "value_count#pageviews":{
                   "value":0
                },
                "cardinality#ips":{
                   "value":0
                }
             },
             {
                "key_as_string":"2020-03-21",
                "key":1584716400000,
                "doc_count":0,
                "cardinality#visitors":{
                   "value":0
                },
                "cardinality#visits":{
                   "value":0
                },
                "value_count#pageviews":{
                   "value":0
                },
                "cardinality#ips":{
                   "value":0
                }
             },
             {
                "key_as_string":"2020-03-22",
                "key":1584802800000,
                "doc_count":0,
                "cardinality#visitors":{
                   "value":0
                },
                "cardinality#visits":{
                   "value":0
                },
                "value_count#pageviews":{
                   "value":0
                },
                "cardinality#ips":{
                   "value":0
                }
             },
             {
                "key_as_string":"2020-03-23",
                "key":1584889200000,
                "doc_count":72,
                "cardinality#visitors":{
                   "value":4
                },
                "cardinality#visits":{
                   "value":4
                },
                "value_count#pageviews":{
                   "value":72
                },
                "cardinality#ips":{
                   "value":1
                }
             },
             {
                "key_as_string":"2020-03-24",
                "key":1584975600000,
                "doc_count":0,
                "cardinality#visitors":{
                   "value":0
                },
                "cardinality#visits":{
                   "value":0
                },
                "value_count#pageviews":{
                   "value":0
                },
                "cardinality#ips":{
                   "value":0
                }
             },
             {
                "key_as_string":"2020-03-25",
                "key":1585062000000,
                "doc_count":0,
                "cardinality#visitors":{
                   "value":0
                },
                "cardinality#visits":{
                   "value":0
                },
                "value_count#pageviews":{
                   "value":0
                },
                "cardinality#ips":{
                   "value":0
                }
             },
             {
                "key_as_string":"2020-03-26",
                "key":1585148400000,
                "doc_count":1,
                "cardinality#visitors":{
                   "value":1
                },
                "cardinality#visits":{
                   "value":1
                },
                "value_count#pageviews":{
                   "value":1
                },
                "cardinality#ips":{
                   "value":1
                }
             },
             {
                "key_as_string":"2020-03-27",
                "key":1585234800000,
                "doc_count":0,
                "cardinality#visitors":{
                   "value":0
                },
                "cardinality#visits":{
                   "value":0
                },
                "value_count#pageviews":{
                   "value":0
                },
                "cardinality#ips":{
                   "value":0
                }
             },
             {
                "key_as_string":"2020-03-28",
                "key":1585321200000,
                "doc_count":0,
                "cardinality#visitors":{
                   "value":0
                },
                "cardinality#visits":{
                   "value":0
                },
                "value_count#pageviews":{
                   "value":0
                },
                "cardinality#ips":{
                   "value":0
                }
             },
             {
                "key_as_string":"2020-03-29",
                "key":1585407600000,
                "doc_count":0,
                "cardinality#visitors":{
                   "value":0
                },
                "cardinality#visits":{
                   "value":0
                },
                "value_count#pageviews":{
                   "value":0
                },
                "cardinality#ips":{
                   "value":0
                }
             },
             {
                "key_as_string":"2020-03-30",
                "key":1585494000000,
                "doc_count":0,
                "cardinality#visitors":{
                   "value":0
                },
                "cardinality#visits":{
                   "value":0
                },
                "value_count#pageviews":{
                   "value":0
                },
                "cardinality#ips":{
                   "value":0
                }
             },
             {
                "key_as_string":"2020-03-31",
                "key":1585580400000,
                "doc_count":7,
                "cardinality#visitors":{
                   "value":1
                },
                "cardinality#visits":{
                   "value":2
                },
                "value_count#pageviews":{
                   "value":7
                },
                "cardinality#ips":{
                   "value":1
                }
             },
             {
                "key_as_string":"2020-04-01",
                "key":1585666800000,
                "doc_count":0,
                "cardinality#visitors":{
                   "value":0
                },
                "cardinality#visits":{
                   "value":0
                },
                "value_count#pageviews":{
                   "value":0
                },
                "cardinality#ips":{
                   "value":0
                }
             },
             {
                "key_as_string":"2020-04-02",
                "key":1585753200000,
                "doc_count":0,
                "cardinality#visitors":{
                   "value":0
                },
                "cardinality#visits":{
                   "value":0
                },
                "value_count#pageviews":{
                   "value":0
                },
                "cardinality#ips":{
                   "value":0
                }
             },
             {
                "key_as_string":"2020-04-03",
                "key":1585839600000,
                "doc_count":0,
                "cardinality#visitors":{
                   "value":0
                },
                "cardinality#visits":{
                   "value":0
                },
                "value_count#pageviews":{
                   "value":0
                },
                "cardinality#ips":{
                   "value":0
                }
             },
             {
                "key_as_string":"2020-04-04",
                "key":1585926000000,
                "doc_count":0,
                "cardinality#visitors":{
                   "value":0
                },
                "cardinality#visits":{
                   "value":0
                },
                "value_count#pageviews":{
                   "value":0
                },
                "cardinality#ips":{
                   "value":0
                }
             },
             {
                "key_as_string":"2020-04-05",
                "key":1586012400000,
                "doc_count":0,
                "cardinality#visitors":{
                   "value":0
                },
                "cardinality#visits":{
                   "value":0
                },
                "value_count#pageviews":{
                   "value":0
                },
                "cardinality#ips":{
                   "value":0
                }
             },
             {
                "key_as_string":"2020-04-06",
                "key":1586098800000,
                "doc_count":0,
                "cardinality#visitors":{
                   "value":0
                },
                "cardinality#visits":{
                   "value":0
                },
                "value_count#pageviews":{
                   "value":0
                },
                "cardinality#ips":{
                   "value":0
                }
             },
             {
                "key_as_string":"2020-04-07",
                "key":1586185200000,
                "doc_count":0,
                "cardinality#visitors":{
                   "value":0
                },
                "cardinality#visits":{
                   "value":0
                },
                "value_count#pageviews":{
                   "value":0
                },
                "cardinality#ips":{
                   "value":0
                }
             },
             {
                "key_as_string":"2020-04-08",
                "key":1586271600000,
                "doc_count":0,
                "cardinality#visitors":{
                   "value":0
                },
                "cardinality#visits":{
                   "value":0
                },
                "value_count#pageviews":{
                   "value":0
                },
                "cardinality#ips":{
                   "value":0
                }
             },
             {
                "key_as_string":"2020-04-09",
                "key":1586358000000,
                "doc_count":1,
                "cardinality#visitors":{
                   "value":1
                },
                "cardinality#visits":{
                   "value":1
                },
                "value_count#pageviews":{
                   "value":1
                },
                "cardinality#ips":{
                   "value":1
                }
             },
             {
                "key_as_string":"2020-04-10",
                "key":1586444400000,
                "doc_count":0,
                "cardinality#visitors":{
                   "value":0
                },
                "cardinality#visits":{
                   "value":0
                },
                "value_count#pageviews":{
                   "value":0
                },
                "cardinality#ips":{
                   "value":0
                }
             },
             {
                "key_as_string":"2020-04-11",
                "key":1586530800000,
                "doc_count":0,
                "cardinality#visitors":{
                   "value":0
                },
                "cardinality#visits":{
                   "value":0
                },
                "value_count#pageviews":{
                   "value":0
                },
                "cardinality#ips":{
                   "value":0
                }
             },
             {
                "key_as_string":"2020-04-12",
                "key":1586617200000,
                "doc_count":0,
                "cardinality#visitors":{
                   "value":0
                },
                "cardinality#visits":{
                   "value":0
                },
                "value_count#pageviews":{
                   "value":0
                },
                "cardinality#ips":{
                   "value":0
                }
             },
             {
                "key_as_string":"2020-04-13",
                "key":1586703600000,
                "doc_count":0,
                "cardinality#visitors":{
                   "value":0
                },
                "cardinality#visits":{
                   "value":0
                },
                "value_count#pageviews":{
                   "value":0
                },
                "cardinality#ips":{
                   "value":0
                }
             },
             {
                "key_as_string":"2020-04-14",
                "key":1586790000000,
                "doc_count":0,
                "cardinality#visitors":{
                   "value":0
                },
                "cardinality#visits":{
                   "value":0
                },
                "value_count#pageviews":{
                   "value":0
                },
                "cardinality#ips":{
                   "value":0
                }
             },
             {
                "key_as_string":"2020-04-15",
                "key":1586876400000,
                "doc_count":0,
                "cardinality#visitors":{
                   "value":0
                },
                "cardinality#visits":{
                   "value":0
                },
                "value_count#pageviews":{
                   "value":0
                },
                "cardinality#ips":{
                   "value":0
                }
             },
             {
                "key_as_string":"2020-04-16",
                "key":1586962800000,
                "doc_count":0,
                "cardinality#visitors":{
                   "value":0
                },
                "cardinality#visits":{
                   "value":0
                },
                "value_count#pageviews":{
                   "value":0
                },
                "cardinality#ips":{
                   "value":0
                }
             },
             {
                "key_as_string":"2020-04-17",
                "key":1587049200000,
                "doc_count":0,
                "cardinality#visitors":{
                   "value":0
                },
                "cardinality#visits":{
                   "value":0
                },
                "value_count#pageviews":{
                   "value":0
                },
                "cardinality#ips":{
                   "value":0
                }
             },
             {
                "key_as_string":"2020-04-18",
                "key":1587135600000,
                "doc_count":0,
                "cardinality#visitors":{
                   "value":0
                },
                "cardinality#visits":{
                   "value":0
                },
                "value_count#pageviews":{
                   "value":0
                },
                "cardinality#ips":{
                   "value":0
                }
             },
             {
                "key_as_string":"2020-04-19",
                "key":1587222000000,
                "doc_count":0,
                "cardinality#visitors":{
                   "value":0
                },
                "cardinality#visits":{
                   "value":0
                },
                "value_count#pageviews":{
                   "value":0
                },
                "cardinality#ips":{
                   "value":0
                }
             },
             {
                "key_as_string":"2020-04-20",
                "key":1587308400000,
                "doc_count":0,
                "cardinality#visitors":{
                   "value":0
                },
                "cardinality#visits":{
                   "value":0
                },
                "value_count#pageviews":{
                   "value":0
                },
                "cardinality#ips":{
                   "value":0
                }
             },
             {
                "key_as_string":"2020-04-21",
                "key":1587394800000,
                "doc_count":64,
                "cardinality#visitors":{
                   "value":4
                },
                "cardinality#visits":{
                   "value":6
                },
                "value_count#pageviews":{
                   "value":64
                },
                "cardinality#ips":{
                   "value":1
                }
             },
             {
                "key_as_string":"2020-04-22",
                "key":1587481200000,
                "doc_count":73,
                "cardinality#visitors":{
                   "value":4
                },
                "cardinality#visits":{
                   "value":7
                },
                "value_count#pageviews":{
                   "value":73
                },
                "cardinality#ips":{
                   "value":1
                }
             },
             {
                "key_as_string":"2020-04-23",
                "key":1587567600000,
                "doc_count":76,
                "cardinality#visitors":{
                   "value":4
                },
                "cardinality#visits":{
                   "value":5
                },
                "value_count#pageviews":{
                   "value":76
                },
                "cardinality#ips":{
                   "value":1
                }
             },
             {
                "key_as_string":"2020-04-24",
                "key":1587654000000,
                "doc_count":42,
                "cardinality#visitors":{
                   "value":2
                },
                "cardinality#visits":{
                   "value":4
                },
                "value_count#pageviews":{
                   "value":42
                },
                "cardinality#ips":{
                   "value":1
                }
             },
             {
                "key_as_string":"2020-04-25",
                "key":1587740400000,
                "doc_count":0,
                "cardinality#visitors":{
                   "value":0
                },
                "cardinality#visits":{
                   "value":0
                },
                "value_count#pageviews":{
                   "value":0
                },
                "cardinality#ips":{
                   "value":0
                }
             },
             {
                "key_as_string":"2020-04-26",
                "key":1587826800000,
                "doc_count":0,
                "cardinality#visitors":{
                   "value":0
                },
                "cardinality#visits":{
                   "value":0
                },
                "value_count#pageviews":{
                   "value":0
                },
                "cardinality#ips":{
                   "value":0
                }
             },
             {
                "key_as_string":"2020-04-27",
                "key":1587913200000,
                "doc_count":27,
                "cardinality#visitors":{
                   "value":3
                },
                "cardinality#visits":{
                   "value":3
                },
                "value_count#pageviews":{
                   "value":27
                },
                "cardinality#ips":{
                   "value":2
                }
             },
             {
                "key_as_string":"2020-04-28",
                "key":1587999600000,
                "doc_count":2,
                "cardinality#visitors":{
                   "value":2
                },
                "cardinality#visits":{
                   "value":1
                },
                "value_count#pageviews":{
                   "value":2
                },
                "cardinality#ips":{
                   "value":1
                }
             }
          ]
       }
    }
 }