{
   "took":20,
   "timed_out":false,
   "_shards":{
      "total":45,
      "successful":45,
      "skipped":0,
      "failed":0
   },
   "hits":{
      "total":0,
      "max_score":null,
      "hits":[

      ]
   },
   "aggregations":{
      "sterms#by_dimension":{
         "doc_count_error_upper_bound":0,
         "sum_other_doc_count":0,
         "buckets":[
            {
               "key":"장바구니",
               "doc_count":35,
               "sum#duration":{
                  "value":96.0
               },
               "cardinality#visitors":{
                  "value":9
               },
               "cardinality#visits":{
                  "value":15
               },
               "value_count#pageviews":{
                  "value":35
               }
            },
            {
               "key":"상품 A 카테고리",
               "doc_count":31,
               "sum#duration":{
                  "value":1698.0
               },
               "cardinality#visitors":{
                  "value":10
               },
               "cardinality#visits":{
                  "value":17
               },
               "value_count#pageviews":{
                  "value":31
               }
            },
            {
               "key":"상품 B 카테고리",
               "doc_count":21,
               "sum#duration":{
                  "value":68.0
               },
               "cardinality#visitors":{
                  "value":7
               },
               "cardinality#visits":{
                  "value":15
               },
               "value_count#pageviews":{
                  "value":21
               }
            },
            {
               "key":"주문 &#62; 주문하기",
               "doc_count":15,
               "sum#duration":{
                  "value":59.0
               },
               "cardinality#visitors":{
                  "value":7
               },
               "cardinality#visits":{
                  "value":13
               },
               "value_count#pageviews":{
                  "value":15
               }
            },
            {
               "key":"상품 D 카테고리",
               "doc_count":14,
               "sum#duration":{
                  "value":257.0
               },
               "cardinality#visitors":{
                  "value":6
               },
               "cardinality#visits":{
                  "value":8
               },
               "value_count#pageviews":{
                  "value":14
               }
            },
            {
               "key":"주문 &#62; 주문결과",
               "doc_count":14,
               "sum#duration":{
                  "value":1238.0
               },
               "cardinality#visitors":{
                  "value":7
               },
               "cardinality#visits":{
                  "value":13
               },
               "value_count#pageviews":{
                  "value":14
               }
            },
            {
               "key":"상품 A 카테고리 > 제조사_F > 브랜드_K",
               "doc_count":9,
               "sum#duration":{
                  "value":9.0
               },
               "cardinality#visitors":{
                  "value":5
               },
               "cardinality#visits":{
                  "value":5
               },
               "value_count#pageviews":{
                  "value":9
               }
            },
            {
               "key":"상품 A 카테고리 > 제조사_G > 브랜드_K",
               "doc_count":8,
               "sum#duration":{
                  "value":14.0
               },
               "cardinality#visitors":{
                  "value":8
               },
               "cardinality#visits":{
                  "value":8
               },
               "value_count#pageviews":{
                  "value":8
               }
            },
            {
               "key":"로그인&#62; 로그인폼",
               "doc_count":7,
               "sum#duration":{
                  "value":23.0
               },
               "cardinality#visitors":{
                  "value":5
               },
               "cardinality#visits":{
                  "value":5
               },
               "value_count#pageviews":{
                  "value":7
               }
            },
            {
               "key":"회원가입&#62; 약관동의",
               "doc_count":7,
               "sum#duration":{
                  "value":16.0
               },
               "cardinality#visitors":{
                  "value":5
               },
               "cardinality#visits":{
                  "value":6
               },
               "value_count#pageviews":{
                  "value":7
               }
            },
            {
               "key":"상품 A 카테고리 > 제조사_H > 브랜드_K",
               "doc_count":6,
               "sum#duration":{
                  "value":7.0
               },
               "cardinality#visitors":{
                  "value":5
               },
               "cardinality#visits":{
                  "value":5
               },
               "value_count#pageviews":{
                  "value":6
               }
            },
            {
               "key":"상품 A 카테고리 > 제조사_H > 브랜드_M",
               "doc_count":6,
               "sum#duration":{
                  "value":12.0
               },
               "cardinality#visitors":{
                  "value":3
               },
               "cardinality#visits":{
                  "value":3
               },
               "value_count#pageviews":{
                  "value":6
               }
            },
            {
               "key":"상품 C 카테고리",
               "doc_count":6,
               "sum#duration":{
                  "value":4.0
               },
               "cardinality#visitors":{
                  "value":5
               },
               "cardinality#visits":{
                  "value":6
               },
               "value_count#pageviews":{
                  "value":6
               }
            },
            {
               "key":"회원가입&#62; 회원가입결과",
               "doc_count":6,
               "sum#duration":{
                  "value":9.0
               },
               "cardinality#visitors":{
                  "value":5
               },
               "cardinality#visits":{
                  "value":6
               },
               "value_count#pageviews":{
                  "value":6
               }
            },
            {
               "key":"회원가입&#62; 회원가입폼",
               "doc_count":6,
               "sum#duration":{
                  "value":14.0
               },
               "cardinality#visitors":{
                  "value":5
               },
               "cardinality#visits":{
                  "value":6
               },
               "value_count#pageviews":{
                  "value":6
               }
            },
            {
               "key":"로그인&#62; 로그인결과",
               "doc_count":4,
               "sum#duration":{
                  "value":4.0
               },
               "cardinality#visitors":{
                  "value":4
               },
               "cardinality#visits":{
                  "value":4
               },
               "value_count#pageviews":{
                  "value":4
               }
            },
            {
               "key":"상품 A 카테고리 > 제조사_F > 브랜드_M",
               "doc_count":4,
               "sum#duration":{
                  "value":29.0
               },
               "cardinality#visitors":{
                  "value":4
               },
               "cardinality#visits":{
                  "value":4
               },
               "value_count#pageviews":{
                  "value":4
               }
            },
            {
               "key":"상품 A 카테고리 > 제조사_G > 브랜드_M",
               "doc_count":4,
               "sum#duration":{
                  "value":2.0
               },
               "cardinality#visitors":{
                  "value":4
               },
               "cardinality#visits":{
                  "value":4
               },
               "value_count#pageviews":{
                  "value":4
               }
            },
            {
               "key":"상품 A 카테고리 > 제조사_H > 브랜드_L",
               "doc_count":4,
               "sum#duration":{
                  "value":143.0
               },
               "cardinality#visitors":{
                  "value":4
               },
               "cardinality#visits":{
                  "value":4
               },
               "value_count#pageviews":{
                  "value":4
               }
            },
            {
               "key":"상품  카테고리",
               "doc_count":3,
               "sum#duration":{
                  "value":15.0
               },
               "cardinality#visitors":{
                  "value":1
               },
               "cardinality#visits":{
                  "value":2
               },
               "value_count#pageviews":{
                  "value":3
               }
            },
            {
               "key":"상품 A 카테고리 > 제조사_F > 브랜드_L",
               "doc_count":3,
               "sum#duration":{
                  "value":21.0
               },
               "cardinality#visitors":{
                  "value":2
               },
               "cardinality#visits":{
                  "value":2
               },
               "value_count#pageviews":{
                  "value":3
               }
            },
            {
               "key":"상품 A 카테고리 > 제조사_G > 브랜드_L",
               "doc_count":3,
               "sum#duration":{
                  "value":1.0
               },
               "cardinality#visitors":{
                  "value":2
               },
               "cardinality#visits":{
                  "value":2
               },
               "value_count#pageviews":{
                  "value":3
               }
            },
            {
               "key":"상품 B 카테고리 > 제조사_H > 브랜드_M",
               "doc_count":2,
               "sum#duration":{
                  "value":2.0
               },
               "cardinality#visitors":{
                  "value":2
               },
               "cardinality#visits":{
                  "value":2
               },
               "value_count#pageviews":{
                  "value":2
               }
            },
            {
               "key":"상품 B 카테고리 > 제조사_F > 브랜드_K",
               "doc_count":1,
               "sum#duration":{
                  "value":0.0
               },
               "cardinality#visitors":{
                  "value":1
               },
               "cardinality#visits":{
                  "value":1
               },
               "value_count#pageviews":{
                  "value":1
               }
            },
            {
               "key":"상품 B 카테고리 > 제조사_F > 브랜드_L",
               "doc_count":1,
               "sum#duration":{
                  "value":4.0
               },
               "cardinality#visitors":{
                  "value":1
               },
               "cardinality#visits":{
                  "value":1
               },
               "value_count#pageviews":{
                  "value":1
               }
            },
            {
               "key":"상품 B 카테고리 > 제조사_F > 브랜드_M",
               "doc_count":1,
               "sum#duration":{
                  "value":1.0
               },
               "cardinality#visitors":{
                  "value":1
               },
               "cardinality#visits":{
                  "value":1
               },
               "value_count#pageviews":{
                  "value":1
               }
            },
            {
               "key":"상품 B 카테고리 > 제조사_G > 브랜드_K",
               "doc_count":1,
               "sum#duration":{
                  "value":1.0
               },
               "cardinality#visitors":{
                  "value":1
               },
               "cardinality#visits":{
                  "value":1
               },
               "value_count#pageviews":{
                  "value":1
               }
            },
            {
               "key":"상품 C 카테고리 > 제조사_F > 브랜드_L",
               "doc_count":1,
               "sum#duration":{
                  "value":3.0
               },
               "cardinality#visitors":{
                  "value":1
               },
               "cardinality#visits":{
                  "value":1
               },
               "value_count#pageviews":{
                  "value":1
               }
            },
            {
               "key":"상품 C 카테고리 > 제조사_G > 브랜드_L",
               "doc_count":1,
               "sum#duration":{
                  "value":1.0
               },
               "cardinality#visitors":{
                  "value":1
               },
               "cardinality#visits":{
                  "value":1
               },
               "value_count#pageviews":{
                  "value":1
               }
            },
            {
               "key":"상품 C 카테고리 > 제조사_H > 브랜드_K",
               "doc_count":1,
               "sum#duration":{
                  "value":1.0
               },
               "cardinality#visitors":{
                  "value":1
               },
               "cardinality#visits":{
                  "value":1
               },
               "value_count#pageviews":{
                  "value":1
               }
            },
            {
               "key":"상품 C 카테고리 > 제조사_H > 브랜드_M",
               "doc_count":1,
               "sum#duration":{
                  "value":1.0
               },
               "cardinality#visitors":{
                  "value":1
               },
               "cardinality#visits":{
                  "value":1
               },
               "value_count#pageviews":{
                  "value":1
               }
            },
            {
               "key":"위시리스트",
               "doc_count":1,
               "sum#duration":{
                  "value":2.0
               },
               "cardinality#visitors":{
                  "value":1
               },
               "cardinality#visits":{
                  "value":1
               },
               "value_count#pageviews":{
                  "value":1
               }
            },
            {
               "key":"이벤트&#62; 상품구매이벤트",
               "doc_count":1,
               "sum#duration":{
                  "value":4.0
               },
               "cardinality#visitors":{
                  "value":1
               },
               "cardinality#visits":{
                  "value":1
               },
               "value_count#pageviews":{
                  "value":1
               }
            }
         ]
      }
   }
}