{
   "took":17,
   "timed_out":false,
   "_shards":{
      "total":45,
      "successful":45,
      "skipped":0,
      "failed":0
   },
   "hits":{
      "total":0,
      "max_score":null,
      "hits":[

      ]
   },
   "aggregations":{
      "sterms#by_dimension":{
         "doc_count_error_upper_bound":0,
         "sum_other_doc_count":0,
         "buckets":[
            {
               "key":"http://demo.logger.co.kr/item/list.php",
               "doc_count":132,
               "sum#duration":{
                  "value":2294.0
               },
               "cardinality#visitors":{
                  "value":14
               },
               "cardinality#visits":{
                  "value":27
               },
               "value_count#pageviews":{
                  "value":132
               }
            },
            {
               "key":"http://demo.logger.co.kr/item/view.php",
               "doc_count":120,
               "sum#duration":{
                  "value":3496.0
               },
               "cardinality#visitors":{
                  "value":14
               },
               "cardinality#visits":{
                  "value":26
               },
               "value_count#pageviews":{
                  "value":120
               }
            },
            {
               "key":"http://demo.logger.co.kr/cart/cart.php",
               "doc_count":35,
               "sum#duration":{
                  "value":96.0
               },
               "cardinality#visitors":{
                  "value":9
               },
               "cardinality#visits":{
                  "value":15
               },
               "value_count#pageviews":{
                  "value":35
               }
            },
            {
               "key":"http://demo.logger.co.kr/",
               "doc_count":17,
               "sum#duration":{
                  "value":38.0
               },
               "cardinality#visitors":{
                  "value":10
               },
               "cardinality#visits":{
                  "value":15
               },
               "value_count#pageviews":{
                  "value":17
               }
            },
            {
               "key":"http://demo.logger.co.kr/order/order.php",
               "doc_count":15,
               "sum#duration":{
                  "value":59.0
               },
               "cardinality#visitors":{
                  "value":7
               },
               "cardinality#visits":{
                  "value":13
               },
               "value_count#pageviews":{
                  "value":15
               }
            },
            {
               "key":"http://demo.logger.co.kr/order/orderSubmit.php",
               "doc_count":14,
               "sum#duration":{
                  "value":1238.0
               },
               "cardinality#visitors":{
                  "value":7
               },
               "cardinality#visits":{
                  "value":13
               },
               "value_count#pageviews":{
                  "value":14
               }
            },
            {
               "key":"http://bizspring.co.kr/website/home/",
               "doc_count":9,
               "sum#duration":{
                  "value":71.0
               },
               "cardinality#visitors":{
                  "value":2
               },
               "cardinality#visits":{
                  "value":4
               },
               "value_count#pageviews":{
                  "value":9
               }
            },
            {
               "key":"http://demo.logger.co.kr/login/login.php",
               "doc_count":7,
               "sum#duration":{
                  "value":23.0
               },
               "cardinality#visitors":{
                  "value":5
               },
               "cardinality#visits":{
                  "value":5
               },
               "value_count#pageviews":{
                  "value":7
               }
            },
            {
               "key":"http://demo.logger.co.kr/register/register.php",
               "doc_count":7,
               "sum#duration":{
                  "value":16.0
               },
               "cardinality#visitors":{
                  "value":5
               },
               "cardinality#visits":{
                  "value":6
               },
               "value_count#pageviews":{
                  "value":7
               }
            },
            {
               "key":"http://demo.logger.co.kr/register/registerInput.php",
               "doc_count":6,
               "sum#duration":{
                  "value":14.0
               },
               "cardinality#visitors":{
                  "value":5
               },
               "cardinality#visits":{
                  "value":6
               },
               "value_count#pageviews":{
                  "value":6
               }
            },
            {
               "key":"http://demo.logger.co.kr/register/registerSubmit.php",
               "doc_count":6,
               "sum#duration":{
                  "value":9.0
               },
               "cardinality#visitors":{
                  "value":5
               },
               "cardinality#visits":{
                  "value":6
               },
               "value_count#pageviews":{
                  "value":6
               }
            },
            {
               "key":"http://demo.logger.co.kr/login/loginSubmit.php",
               "doc_count":4,
               "sum#duration":{
                  "value":4.0
               },
               "cardinality#visitors":{
                  "value":4
               },
               "cardinality#visits":{
                  "value":4
               },
               "value_count#pageviews":{
                  "value":4
               }
            },
            {
               "key":"http://demo.logger.co.kr/index.php",
               "doc_count":2,
               "sum#duration":{
                  "value":0.0
               },
               "cardinality#visitors":{
                  "value":2
               },
               "cardinality#visits":{
                  "value":2
               },
               "value_count#pageviews":{
                  "value":2
               }
            },
            {
               "key":"http://demo.logger.co.kr/event/event.php",
               "doc_count":1,
               "sum#duration":{
                  "value":4.0
               },
               "cardinality#visitors":{
                  "value":1
               },
               "cardinality#visits":{
                  "value":1
               },
               "value_count#pageviews":{
                  "value":1
               }
            },
            {
               "key":"http://demo.logger.co.kr/wish/wish.php",
               "doc_count":1,
               "sum#duration":{
                  "value":2.0
               },
               "cardinality#visitors":{
                  "value":1
               },
               "cardinality#visits":{
                  "value":1
               },
               "value_count#pageviews":{
                  "value":1
               }
            },
            {
               "key":"http://demo11.logger.co.kr/",
               "doc_count":1,
               "sum#duration":{
                  "value":0.0
               },
               "cardinality#visitors":{
                  "value":1
               },
               "cardinality#visits":{
                  "value":1
               },
               "value_count#pageviews":{
                  "value":1
               }
            }
         ]
      }
   }
}