{
   "data":[
      {
         "dimension":"http:\/\/demo.logger.co.kr\/item\/list.php",
         "pageviews":132,
         "visits":27,
         "visitors":14,
         "duration":2294
      },
      {
         "dimension":"http:\/\/demo.logger.co.kr\/item\/view.php",
         "pageviews":120,
         "visits":26,
         "visitors":14,
         "duration":3496
      },
      {
         "dimension":"http:\/\/demo.logger.co.kr\/cart\/cart.php",
         "pageviews":35,
         "visits":15,
         "visitors":9,
         "duration":96
      },
      {
         "dimension":"http:\/\/demo.logger.co.kr\/",
         "pageviews":17,
         "visits":15,
         "visitors":10,
         "duration":38
      },
      {
         "dimension":"http:\/\/demo.logger.co.kr\/order\/order.php",
         "pageviews":15,
         "visits":13,
         "visitors":7,
         "duration":59
      },
      {
         "dimension":"http:\/\/demo.logger.co.kr\/order\/orderSubmit.php",
         "pageviews":14,
         "visits":13,
         "visitors":7,
         "duration":1238
      },
      {
         "dimension":"http:\/\/bizspring.co.kr\/website\/home\/",
         "pageviews":9,
         "visits":4,
         "visitors":2,
         "duration":71
      },
      {
         "dimension":"http:\/\/demo.logger.co.kr\/login\/login.php",
         "pageviews":7,
         "visits":5,
         "visitors":5,
         "duration":23
      },
      {
         "dimension":"http:\/\/demo.logger.co.kr\/register\/register.php",
         "pageviews":7,
         "visits":6,
         "visitors":5,
         "duration":16
      },
      {
         "dimension":"http:\/\/demo.logger.co.kr\/register\/registerInput.php",
         "pageviews":6,
         "visits":6,
         "visitors":5,
         "duration":14
      },
      {
         "dimension":"http:\/\/demo.logger.co.kr\/register\/registerSubmit.php",
         "pageviews":6,
         "visits":6,
         "visitors":5,
         "duration":9
      },
      {
         "dimension":"http:\/\/demo.logger.co.kr\/login\/loginSubmit.php",
         "pageviews":4,
         "visits":4,
         "visitors":4,
         "duration":4
      },
      {
         "dimension":"http:\/\/demo.logger.co.kr\/index.php",
         "pageviews":2,
         "visits":2,
         "visitors":2,
         "duration":0
      },
      {
         "dimension":"http:\/\/demo.logger.co.kr\/event\/event.php",
         "pageviews":1,
         "visits":1,
         "visitors":1,
         "duration":4
      },
      {
         "dimension":"http:\/\/demo.logger.co.kr\/wish\/wish.php",
         "pageviews":1,
         "visits":1,
         "visitors":1,
         "duration":2
      },
      {
         "dimension":"http:\/\/demo11.logger.co.kr\/",
         "pageviews":1,
         "visits":1,
         "visitors":1,
         "duration":0
      }
   ]
}