{
   "index":"pageview-*",
   "body":{
      "query":{
         "bool":{
            "must":{
               "terms":{
                  "pfno":[
                     "12845",
                     "23884"
                  ]
               }
            },
            "must_not":{
               "term":{
                  "du_dp.full":""
               }
            },
            "filter":{
               "range":{
                  "vt":{
                     "gte":"2020-03-01T00:00:00+0900",
                     "lte":"2020-05-01T23:59:59+0900"
                  }
               }
            }
         }
      },
      "aggs":{
         "by_dimension":{
            "terms":{
               "field":"du_dp.full",
               "size":200,
               "order":{
                  "pageviews":"desc"
               }
            },
            "aggs":{
               "pageviews":{
                  "value_count":{
                     "fie ld":"_id"
                  }
               },
               "visits":{
                  "cardinality":{
                     "field":"sid"
                  }
               },
               "visitors":{
                  "cardinality":{
                     "field":"uid"
                  }
               },
               "duration":{
                  "sum":{
                     "field":"duration",
                     "missing":0
                  }
               }
            }
         }
      }
   }
}