{
   "index":"pageview-*",
   "body":{
      "query":{
         "bool":{
            "must":{
               "terms":{
                  "pfno":[
                     "12845",
                     "23884"
                  ]
               }
            },
            "filter":{
               "range":{
                  "vt":{
                     "gte":"2020-03-01T00:00:00+0900",
                     "lte":"2020-05-01T23:59:59+0900"
                  }
               }
            }
         }
      },
      "aggs":{
         "by_date":{
            "date_histogram":{
               "field":"vt",
               "fixed_interval":"1d",
               "format":"yyyy-MM-dd",
               "time_zone":"Asia\/Seoul",
               "min_doc_count":0
            },
            "aggs":{
               "cartin":{
                  "sum":{
                    "script":{
                        "source":"doc['pi'].size() != 0 && doc['pi'].value == 'OCI' ? 1 : 0"
                    }
                  }
               },
               "buy":{
                  "sum":{
                     "script":{
                        "source":"doc['pi'].size() != 0 && doc['pi'].value == 'ODR' ? 1 : 0"
                     }
                  }
               },
               "revenue":{
                  "sum":{
                     "field":"rvn.oa"
                  }
               },
               "register":{
                  "sum":{
                     "script":{
                        "source":"doc['pi'].size() != 0 && doc['pi'].value == 'RGR' ? 1 : 0"
                     }
                  }
               },
               "solditem":{
                  "cardinality":{
                     "field":"rvn.op"
                  }
               }
            }
         }
      }
   }
}